### ISSUE TITLE
Rewrite mpets for the following armor stand pet

### ISSUE THREAD

**Issue by WakkaFlocka239** [ProjectEdenGG/Issues#230] opened 2018-12-20 07:20 UTC
The /mpet menu is broken for multiple pages.

The navigation buttons disappear and console goes nuts.

**Comment by FilidDamhsoir** [comment] 2018-12-21 16:32
https://docs.google.com/spreadsheets/d/1u4EEHTDYt1oT0LcvL9OU20p_HVJrv9Us0K3p7mkgw_U/edit?usp=sharing

that's all the pets that appear in my menus on the main and the test servers

meanwhile.  1. Appear to be a number of pets missing.  I should have all pet perms but, I only have  ~40 of the 72 pets in the pets folder in the smp plugins folder? Am I missing perm node or are they broken?
2. Still no penguin and I *DO* have his perm

3. This is how the menus appear on the test:
https://gyazo.com/1dbc2ca6b6006945ea31cb12d54c1bd8
https://gyazo.com/84ae50a6cd6b2fa85f66bd8c7ea07e60
https://gyazo.com/0d9b090179d72fef66e22599b67f58f4

This is them on the main
https://gyazo.com/feecb63af3ff54617f917146ed5c49b4
https://gyazo.com/9c6956f2a0aed9c6e8f9dcaf8bea118b

**Comment by WakkaFlocka239** [comment] 2019-07-16 23:57
Are we going to completely remove this plugin from the server, or try and get a fixed version?

**Comment by Pugabyte** [comment] 2021-02-28 06:21
Would like to replace this plugin with our own code, simple for the floating head pet (no custom models)

**Comment by GriffinCodes** [comment] 2021-06-04 20:29
duplicate of #22

**Closed by GriffinCodes** 2021-06-04 20:29 UTC
Labels: bug, plugin
